### ISSUE TITLE
Enum/Type not working in Uplink 2.0

### ISSUE THREAD

**Issue by Pyrobolser** [adjoint-io/fcl#37]
Hello, I tried to have a working enumeration as explained [here in the documentation](https://www.adjoint.io/docs/workflows.html#enumeration-types).

I cannot get anything working... I also tried to copy/paste numerous the examples that I found here in the test folders but nothing was working.

Can you please provide a working example using an enumeration like the Color case explained in the documentation?

Thank you

**Comment by buggymcbugfix** [comment]
All the example scripts will work with the matching version of `fcl`, since this is checked in the test suite. Which command are you running?

**Comment by Pyrobolser** [comment]
For example, with the latest version of Uplink, I am trying to put this contract from the examples with the Python SDK method `create_contract`

```
type point { P(int x, int y) }

global int x;
global int y;

@initial
foo(point p) {
  x = case p {P(x1, _) -> x1};
  y = case p {P(_, y1) -> y1};
  terminate()
}
```

But I get the following error
```UplinkJsonRpcError: ("Malformed Transaction: <Transaction(signature=b'AE00MjY4ODgwNjEzNDE0MTcxMTA1MDQ4MzI5NTM5NjczNjUzMDM0NTYxMTQ2MTc3MjYxODM5NjI4NzQzOTcwNjY1NTM3OTI4OTY0NzQyMToATjExMzk1NTM1MjQwNzQyMjEzNDE4MTA2MDk2MTUyMjgxMDU2MTYyNzAwMTk4MjkzODc5NzQ5NTkwNDkyMTkzNjU2NjI1MDgyNjE0MDA2MQ==')>", {'tag': 'RPCRespError', 'contents': {'errorMsg': 'Error in $.params.header.contents: type point { P(int x, int y) }\n    \n-----^\n    \n    global int x;\n\n"<stdin>" (line 1, column 6):\nunexpected "p"\nexpecting uppercase letter', 'errorType': 'JSONParse'}})```
